# 基础镜像
# FROM nacos/nacos-server
FROM registry.cn-hangzhou.aliyuncs.com/lsc_2/nacos-server:v2.0.4

# author
MAINTAINER ruoyi

# 复制conf文件到路径
COPY ./conf/application.properties /home/nacos/conf/application.properties
